config/routes.rb
Rails.application.routes.draw do
  resources :pages
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#index"
  get '/packages', to: 'pages#packages'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/page.rb
# == Schema Information
#
# Table name: pages
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Page < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_forgery_protection
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: %i[ show edit update destroy ]

  # GET /pages or /pages.json
  def index
    @pages = Page.all
  end

  # GET /pages/1 or /pages/1.json
  def show
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit
  end

  def packages
  end

  # POST /pages or /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to page_url(@page), notice: "Page was successfully created." }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1 or /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to page_url(@page), notice: "Page was successfully updated." }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1 or /pages/1.json
  def destroy
    @page.destroy

    respond_to do |format|
      format.html { redirect_to pages_url, notice: "Page was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Page.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def page_params
      params.fetch(:page, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Modern Realty Studios</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'style', media: 'all', 'data-turbo-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans|Raleway:300,400" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/modal.html.erb
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

app/views/pages/_form.html.erb
<%= form_with(model: page) do |form| %>
  <% if page.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
        <% page.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pages/_page.html.erb
<div id="<%= dom_id page %>">
</div>

app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= render "form", page: @page %>

<br>

<div>
  <%= link_to "Show this page", @page %> |
  <%= link_to "Back to pages", pages_path %>
</div>

app/views/pages/index.html.erb
<div class="container">
  <div class="text-section">
    <h1>Modern Realty Studios</h1>
    <p>Welcome to Modern Realty Studios, your trusted partner for exceptional real estate photography in the Chicagoland area. We are dedicated to providing clean and professional media that showcases your property in the best light possible.</p>
    <button>Book us</button>
  </div>
  <div class="img">
    <%= image_tag('house/house.jpeg', alt: 'House', width: '500px') %>
  </div>
</div>
<div class="mid-text">
  <h2> Our skilled photographers capture the essence of each listing, highlighting unique features.</h2>
  <h3>We bring your vision into a reality.</h3>
</div>
<div class="row">
  <div class="column">
    <%= image_tag('kitchen/kitchen.jpeg', alt: 'Landscape', width: '100%') %>
  </div>
  <div class="column">
    <%= image_tag('livingroom/livingroom.jpeg', alt: 'Landscape', width: '100%') %>
  </div>
  <div class="column">
    <%= image_tag('landscape/landscape.jpeg', alt: 'Landscape', width: '100%') %>
  </div>
</div>
<div class="container">
  <div class="img">
    <%= image_tag('house/house6.jpeg', alt: 'House', width: '500px') %>
  </div>
  <div class="text-section">
    <h2>Elevate your listings.</h2>
    <p>With a commitment to excellence, we deliver high quality photos that make lasting impressions on potential buyers.</p>
    <button>Learn More</button>
  </div>
<!---->
<%#= link_to "New page", new_page_path %>

app/views/pages/new.html.erb
<h1>New page</h1>

<%= render "form", page: @page %>

<br>

<div>
  <%= link_to "Back to pages", pages_path %>
</div>

app/views/pages/packages.html.erb
<h1>Packages</h1>
<div class="container">
  <div class="img">
    <%= image_tag('house/house.jpeg', alt: 'House', width: '500px') %>
  </div>
  <div class="text-section">
    <h3>Photos</h3>
    <p>Our photos packages are as listed.</p>
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#photoModal">
      Pricing
    </button>
  </div>
</div>
<div class="modal fade" id="photoModal" tabindex="-1" aria-labelledby="photoModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="examplefirstModalLabel">Pricing</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <table class="table">
          <thead>
            <tr>
              <th scope="col">Package</th>
              <th scope="col">Price</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <th scope="row">10 Photos</th>
              <td>$150.00</td>
            </tr>
            <tr>
              <th scope="row">20 Photos</th>
              <td>$175.00</td>
            </tr>
            <tr>
              <th scope="row">30 Photos</th>
              <td>$200.00</td>
            </tr>
            <tr>
              <th scope="row">40 Photos</th>
              <td>$225.00</td>
            </tr>
            <tr>
              <th scope="row">50 Photos</th>
              <td>$250.00</td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="text-section">
    <h3>Detail Shots</h3>
    <p>Our detail shots packages are as listed.</p>
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#detailModal">
      Pricing
    </button>
  </div>
  <div class="img">
    <%= image_tag('house/house3.jpeg', alt: 'House', width: '500px') %>
  </div>
</div>
<div class="modal fade" id="detailModal" tabindex="-1" aria-labelledby="detailModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Pricing</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <table class="table">
          <thead>
            <tr>
              <th scope="col">Package</th>
              <th scope="col">Price</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <th scope="row">10 Detail Photos</th>
              <td>$50.00</td>
            </tr>
            <tr>
              <th scope="row">20 Detail Photos</th>
              <td>$100.00</td>
            </tr>
            <tr>
              <th scope="row">5 Drone Photos</th>
              <td>$200.00</td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="img">
    <%= image_tag('livingroom/livingroom1.jpeg', alt: 'House', width: '500px') %>
  </div>
  <div class="text-section">
    <h3>Floor Plans</h3>
    <p>Our detail shots packages are as listed.</p>
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#floorModal">
      Pricing
    </button>
  </div>
</div>
<div class="modal fade" id="floorModal" tabindex="-1" aria-labelledby="floorModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Pricing</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <table class="table">
          <thead>
            <tr>
              <th scope="col">Package</th>
              <th scope="col">Price</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <th scope="row">Single Floor</th>
              <td>$75.00</td>
            </tr>
            <tr>
              <th scope="row">2 Floors</th>
              <td>$150.00</td>
            </tr>
            <tr>
              <th scope="row">3 Floors</th>
              <td>$200.00</td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/pages/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @page %>

<div>
  <%= link_to "Edit this page", edit_page_path(@page) %> |
  <%= link_to "Back to pages", pages_path %>

  <%= button_to "Destroy this page", @page, method: :delete %>
</div>